customhost = "my-intern-project.cds0cw4ealo3.us-east-1.rds.amazonaws.com"
customuser = "karthik"
custompass = "karthik1997"
customdb = "employee"
custombucket = "karthik103"
customregion = "us-east-1"
