customhost = "employee.clcaks4qs9xp.ap-southeast-1.rds.amazonaws.com"
customuser = "Intellipaat "
custompass = "karthik1997"
customdb = "employee"
custombucket = "addemployee19"
customregion = "ap-southeast-1"
